### ISSUE TITLE
is it active?

### ISSUE THREAD

**Issue by rogerlz** [majianjia/DeepPlankter#1]
Hello!

Wondering if your project is still active? Do you have any socials to follow the progress and maybe even interact with you and other builders, if any (e.g. Discord/Slack?)

Ty
Roger

**Comment by majianjia** [comment]
No sorry it is put into a pause. 
There will be another update but it is about an experiment early last year, the experiment wasnt complete so I didnt write a log however it would never be completed now. I may a video to summary the findings. 
I relocated half-year ago, and couldn't carry it with me. It was given to a local RC hobbyist. 

The hull design and hydrowings arent effectively during my test. 
I may restart the project with a different design and a completely new hull building in the coming years.  

Thanks

**Comment by rogerlz** [comment]
Thank you for the reply. I can't wait to see what's coming next :)
