### ISSUE TITLE
Continuing the project.

### ISSUE THREAD

**Issue by felixJ86** [majianjia/DeepPlankter#2]
Hi as you may have notice i have made a fork of this project. and this is because i would like to continue this project. and if possible would like to get my hands on the source code as well. is this ok with you?

**Comment by majianjia** [comment]
Yes I am fine, thank you! Thanks for your interest. 
Please refer to https://github.com/majianjia/DeepPlankter/issues/1#issuecomment-1369482837 for the current status of this project. 
There is still some security info that needs to be cleaned before it can be released, never have a chance to do it. 
I will check today.

**Comment by felixJ86** [comment]
ok thank you.
